### ISSUE TITLE
возможность включения-отключения баз в браузерном расширении

### ISSUE THREAD

**Issue by vavy** [cyberdonos/cyberdonos-browser-extension#1]
Здравствуйте,
пожалуйста добавьте в настройки браузерного расширения возможность включать-выключать проверку по отдельным базам.
Я, в частности, хотел бы выключить базу "Карателя", так как по-моему в ней слишком много false-positive записей.
Спасибо!

**Comment by cyberdonos** [comment]
Привет! Извини, только заметил твою ишью. 

А что разве настройках расширения это нет? Есть же. Ну по крайней мере в хроме работает точно.
![IMG_20190820_082950_468](https://user-images.githubusercontent.com/43920181/63310464-082ec580-c325-11e9-91ce-8b50b24b5cca.jpg)
